export const projectList = [
  {
    name: "Afternuage",
    tech: "Next.js, Tailwind, shadcn/ui, Clerk",
    imageUrl: "/images/afternuage.jpeg",
    filter: "Next.js,React.js,Tailwind",
    href: "https://afternuage.com",
    viewUrl: "https://afternuage.com",
    view: ["View"],
  },
  {
    name: "Finance",
    tech: "Next.js, Tailwind, shadcn/ui, PostgreSQL, Hono",
    imageUrl: "/images/finance.png",
    filter: "Next.js,React.js,Node.js,MongoDB,Tailwind,firebase",
    href: "https://github.com/venilsutariya/Finance",
    viewUrl: "https://github.com/venilsutariya/Finance",
    view: ["Github"],
  },
  {
    name: "TatvaTech",
    tech: "Next.js, Tailwind, shadcn/ui, Framer-Motion",
    imageUrl: "/images/tatvatech.jpg",
    filter: "Next.js,Tailwind",
    href: "https://tatvatech.vercel.app/",
    viewUrl: "https://tatvatech.vercel.app/",
    view: ["View"],
  },
  {
    name: "Shilp",
    tech: "Next.js, Node.js ,MongoDB, Tailwind, shadcn/ui",
    imageUrl: "/images/shilp.png",
    filter: "React.js,Node.js,MongoDB,Tailwind,firebase",
    href: "https://shilp.co",
    viewUrl: "https://shilp.co",
    view: ["View"],
  },
  {
    name: "Sitenote",
    tech: "React.js, Node.js ,MongoDB, Tailwind, shadcn/ui",
    imageUrl: "/images/sitenote.webp",
    filter: "React.js,Node.js,MongoDB,Tailwind,firebase",
    href: "https://sitenote.in",
    viewUrl: "https://sitenote.in",
    view: ["View"],
  },
  {
    name: "Spotify Clone",
    tech: "Next.js 13, React.js, Supabase, Typescript",
    imageUrl: "/images/spotify-clone.webp",
    href: "https://github.com/venilsutariya/spotify-clone.git",
    filter: "Next.js,Clerk,Supabase,Typescript",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/spotify-clone.git",
  },
  {
    name: "Spark",
    tech: "Next.js 13, React.js, Tailwind, Clerk, Convex",
    imageUrl: "/images/spark.png",
    href: "https://spark-omega.vercel.app/",
    filter: "Next.js,Tailwind,Clerk,Typescript",
    view: ["View", "Github"],
    viewUrl: "https://spark-omega.vercel.app/",
    githubUrl: "https://github.com/venilsutariya/spark",
  },
  {
    name: "BookmyBox",
    tech: "Nodejs, nodemailer, express, MongoDB",
    imageUrl: "/images/bookmybox.png",
    href: "https://github.com/venilsutariya/BookmyBoxbackend",
    filter: "Node.js,MongoDB,express,Typescript",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/BookmyBoxbackend",
  },
  {
    name: "Discord Clone",
    tech: "Next.js, React.js, Shadcn, Typescript, Tailwind",
    imageUrl: "/images/discord-clone.webp",
    href: "https://github.com/venilsutariya/discord-clone",
    filter: "Next.js,Clerk,Shadcn,Typescript",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/discord-clone",
  },
  {
    name: "Messanger Clone",
    tech: "Next.js 13, React.js, Tailwind, MongoDB",
    imageUrl: "/images/messanger.webp",
    href: "https://github.com/venilsutariya/messanger-clone",
    filter: "Next.js,Tailwind,Next Auth,Typescript",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/messanger-clone",
  },
  {
    name: "Next Auth",
    tech: "Next.js 13, React.js, Tailwind, shadcn/ui",
    imageUrl: "/images/nextauth.png",
    href: "https://github.com/venilsutariya/Next-Auth",
    filter: "Next.js,Tailwind,Next Auth,Typescript",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/Next-Auth",
  },
  {
    name: "AI-SaaS image generator",
    tech: "React.js, Node.js ,Cloudinary",
    imageUrl: "/images/imaginify.png",
    href: "https://github.com/venilsutariya/AI-SaaS-Image-Generator",
    filter: "React.js,Node.js,MongoDB,Tailwind",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/AI-SaaS-Image-Generator",
  },
  {
    name: "AI Talks",
    tech: "React.js, Node.js ,Cloudinary",
    imageUrl: "/images/ai-talks.svg",
    href: "https://github.com/venilsutariya/ai.talks",
    filter: "React.js,Next.js,Prisma,Tailwind,OpenAI",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/ai.talks",
  },
  {
    name: "E-commerce",
    tech: "React.js, Node.js ,MongoDB, Tailwind",
    imageUrl: "/images/ecommerce.webp",
    href: "https://github.com/venilsutariya/E-commerce",
    filter: "React.js,Node.js,MongoDB",
    view: ["Github"],
    githubUrl: "https://github.com/venilsutariya/E-commerce",
  },
];
